DELETE FROM film_likes;
DELETE FROM film_genre;
DELETE FROM friendship;
DELETE FROM films;
DELETE FROM users;
DELETE FROM genres;
DELETE FROM rating;

ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1;
ALTER TABLE films ALTER COLUMN film_id RESTART WITH 1;
ALTER TABLE rating ALTER COLUMN rating_id RESTART WITH 1;
ALTER TABLE genres ALTER COLUMN genre_id RESTART WITH 1;